### ISSUE TITLE
There is something wrong with the build_canonical script

### ISSUE THREAD

**Issue by emilleishida** [COINtoolbox/RESSPECT#1]

**Comment by emilleishida** [comment]
I keep getting

`Traceback (most recent call last):
  File "/home/emille/Documents/git/COIN/RESSPECT/venv/RESSPECT_new_repo/resspect/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'orig_sample'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/emille/Documents/git/COIN/RESSPECT/venv/RESSPECT_new_repo/resspect/bin/build_canonical.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/emille/Documents/git/COIN/RESSPECT/RESSPECT_repo/RESSPECT/resspect/scripts/build_canonical.py", line 123, in <module>
    main(from_user)
  File "/home/emille/Documents/git/COIN/RESSPECT/RESSPECT_repo/RESSPECT/resspect/scripts/build_canonical.py", line 69, in main
    plot_snpcc_train_canonical(sample, user_choices.output_plot_file)
  File "/home/emille/Documents/git/COIN/RESSPECT/RESSPECT_repo/RESSPECT/resspect/build_snpcc_canonical.py", line 358, in plot_snpcc_train_canonical
    canonical_flag = sample.canonical_sample['orig_sample'] == 'queryable'
  File "/home/emille/Documents/git/COIN/RESSPECT/venv/RESSPECT_new_repo/resspect/lib/python3.6/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/emille/Documents/git/COIN/RESSPECT/venv/RESSPECT_new_repo/resspect/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'orig_sample'`
