### ISSUE TITLE
problem with infinits

### ISSUE THREAD

**Issue by emilleishida** [COINtoolbox/RESSPECT#29]
I was trying to run the batch strategies with PLAsTiCC and I got

`Traceback (most recent call last):`

  `File "run_AL_loop.py", line 46, in <module>
    survey=survey, queryable=queryable, n_estimators=n_estimators, save_full_query=save_full_query)`

  `File "/media/emille/git/COIN/RESSPECT_repo/RESSPECT/resspect/time_domain_loop.py", line 297, in time_domain_loop
    screen=False)`

  `File "/media/emille/git/COIN/RESSPECT_repo/RESSPECT/resspect/database.py", line 1069, in make_query_budget
    criteria="uncertainty" )`

  `File "/media/emille/git/COIN/RESSPECT_repo/RESSPECT/resspect/query_budget_strategies.py", line 16, in batch_queries_uncertainty`

    `cost_4m[cost_4m >= 9999] = np.inf`

`OverflowError: cannot convert float infinity to integer`

for some reason it does not like it.

the code I used to generate this error is at:

`/media/RESSPECT/code/for_batch_strategies/run_AL_loop.py`

**Comment by emilleishida** [comment]
to get this error you need to be in the `plasticc` branch

**Comment by emilleishida** [comment]
fixed by removing infinits
