### ISSUE TITLE
error in multiple batch strategies

### ISSUE THREAD

**Issue by emilleishida** [COINtoolbox/RESSPECT#53]
I think the `batch_queries_uncertainty` function needs an exception when there is not enough objects to build many batches. 

I am getting the following error, when I try to generate 3 batches in the `multiple_batch_selection` branch: 

 Metrics names:  ['accuracy', 'efficiency', 'purity', 'fom']
Metrics values:  [0.6913191076624636, 0.44495980210265923, 0.6570776255707762, 0.17342826522907007]
Traceback (most recent call last):
  File "run_AL.py", line 63, in <module>
    output_fname=output_fname, num_batches=num_batches)
  File "/media/emille/git/COIN/RESSPECT_repo/venv/resspect_main/lib/python3.7/site-packages/resspect-0.1-py3.7.egg/resspect/time_domain_loop.py", line 314, in time_domain_loop
  File "/media/emille/git/COIN/RESSPECT_repo/venv/resspect_main/lib/python3.7/site-packages/resspect-0.1-py3.7.egg/resspect/database.py", line 1190, in make_query_budget
  File "/media/emille/git/COIN/RESSPECT_repo/venv/resspect_main/lib/python3.7/site-packages/resspect-0.1-py3.7.egg/resspect/query_budget_strategies.py", line 97, in batch_queries_uncertainty
  File "/media/emille/git/COIN/RESSPECT_repo/venv/resspect_main/lib/python3.7/site-packages/scipy/special/_logsumexp.py", line 215, in softmax
    return np.exp(x - logsumexp(x, axis=axis, keepdims=True))
  File "/media/emille/git/COIN/RESSPECT_repo/venv/resspect_main/lib/python3.7/site-packages/scipy/special/_logsumexp.py", line 101, in logsumexp
    a_max = np.amax(a, axis=axis, keepdims=True)
  File "<__array_function__ internals>", line 6, in amax
  File "/media/emille/git/COIN/RESSPECT_repo/venv/resspect_main/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2668, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/media/emille/git/COIN/RESSPECT_repo/venv/resspect_main/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by emilleishida** [comment]
actually this error occur even when I use `num_batches=1`. Maybe it is something else.
