### ISSUE TITLE
bug in time domain QBD strategies

### ISSUE THREAD

**Issue by emilleishida** [COINtoolbox/RESSPECT#67]
Whenever trying to use QBDEntropy or QBDMI with batches in the data stored at

path_to_ini_files['train'] = '/media/RESSPECT/data/SNPCC/bazin/IAL2020/realistic/Train.csv'
path_to_ini_files['test'] = '/media/RESSPECT/data/SNPCC/bazin/IAL2020/realistic/Test.csv'
path_to_ini_files['validation'] = '/media/RESSPECT/data/SNPCC/bazin/IAL2020/realistic/Validation.csv'
path_to_features_dir = '/media/RESSPECT/data/SNPCC/bazin/IAL2020/realistic/pool/'

I get the following error:

 ****************************
 Processing night:  20 

 Before update_samples:
   ... train:  10
   ... test:  1000
   ... validation:  1000
   ... pool:  3605 

 Inside classify: 
   ... train_features:  (10, 20)
   ... train_labels:  (10,)
   ... pool_features:  (3605, 20)

 Metrics names:  ['accuracy', 'efficiency', 'purity', 'fom']
Metrics values:  [0.452, 0.7321428571428571, 0.25153374233128833, 0.07375394875394876]
Traceback (most recent call last):
  File "learn_loop_timedomain.py", line 65, in <module>
    survey=survey, queryable=queryable, n_estimators=n_estimators)
  File "/media/emille/git/COIN/RESSPECT_repo/RESSPECT/resspect/time_domain_loop.py", line 298, in time_domain_loop
    screen=False)
  File "/media/emille/git/COIN/RESSPECT_repo/RESSPECT/resspect/database.py", line 1219, in make_query_budget
    criteria="entropy" )
  File "/media/emille/git/COIN/RESSPECT_repo/RESSPECT/resspect/query_budget_strategies.py", line 163, in batch_queries_mi_entropy
    probs_B_K_C = probs_B_K_C[pool_query_filter]
TypeError: 'NoneType' object is not subscriptable

**Comment by emilleishida** [comment]
This was stupidity of my own. 
everything is fine.
